name: Trivy Scan
description: Run Trivy filesystem scan with optional SARIF upload.
inputs:
  scan_path:
    description: Path to scan.
    default: "."
    required: false
  format:
    description: Trivy output format.
    default: sarif
    required: false
  output:
    description: Output file path for Trivy results.
    default: trivy-results.sarif
    required: false
  severity:
    description: Comma-separated severities to report.
    default: CRITICAL,HIGH
    required: false
  ignore_unfixed:
    description: Ignore unfixed vulnerabilities.
    default: "true"
    required: false
  vuln_type:
    description: Comma-separated vulnerability types.
    default: os,library
    required: false
  fail_on_findings:
    description: Fail the workflow when findings match severity.
    default: "false"
    required: false
  upload_sarif:
    description: Upload SARIF to GitHub Security tab when format is sarif.
    default: "true"
    required: false
runs:
  using: composite
  steps:
    - name: Run Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: ${{ inputs.scan_path }}
        format: ${{ inputs.format }}
        output: ${{ inputs.output }}
        severity: ${{ inputs.severity }}
        ignore-unfixed: ${{ inputs.ignore_unfixed }}
        vuln-type: ${{ inputs.vuln_type }}
        exit-code: ${{ inputs.fail_on_findings == 'true' && '1' || '0' }}
    - name: Upload SARIF
      if: ${{ inputs.upload_sarif == 'true' && inputs.format == 'sarif' }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ inputs.output }}
