name: Gitleaks Scan
description: Run Gitleaks scan and emit a report.
inputs:
  scan_path:
    description: Path to scan (relative to repo root).
    default: "."
    required: false
  report_format:
    description: Report format (json or sarif).
    default: json
    required: false
  output:
    description: Output report file path.
    default: gitleaks-report.json
    required: false
  config_path:
    description: Optional Gitleaks config file path.
    default: ""
    required: false
  fail_on_findings:
    description: Fail when findings are detected.
    default: "false"
    required: false
runs:
  using: composite
  steps:
    - name: Prepare report path
      shell: bash
      run: |
        set -euo pipefail
        output="${{ inputs.output }}"
        mkdir -p "$(dirname "$output")"
    - name: Gitleaks scan (default config)
      if: ${{ inputs.config_path == '' }}
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        args: >-
          detect
          --source="${{ inputs.scan_path }}"
          --report-format="${{ inputs.report_format }}"
          --report-path="${{ inputs.output }}"
          --exit-code=0
    - name: Gitleaks scan (custom config)
      if: ${{ inputs.config_path != '' }}
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        args: >-
          detect
          --source="${{ inputs.scan_path }}"
          --config="${{ inputs.config_path }}"
          --report-format="${{ inputs.report_format }}"
          --report-path="${{ inputs.output }}"
          --exit-code=0
    - name: Evaluate findings
      shell: bash
      run: |
        set -euo pipefail
        report_format="${{ inputs.report_format }}"
        output="${{ inputs.output }}"
        fail_on_findings="${{ inputs.fail_on_findings }}"

        python3 - <<'PY'
        import json
        import os
        import sys

        report_format = os.environ["REPORT_FORMAT"]
        output = os.environ["OUTPUT"]
        fail_on_findings = os.environ["FAIL_ON_FINDINGS"] == "true"

        count = 0
        if report_format == "sarif":
            with open(output, "r", encoding="utf-8") as fh:
                data = json.load(fh)
            runs = data.get("runs", [])
            for run in runs:
                results = run.get("results", [])
                if isinstance(results, list):
                    count += len(results)
        else:
            with open(output, "r", encoding="utf-8") as fh:
                data = json.load(fh)
            if isinstance(data, list):
                count = len(data)
            elif isinstance(data, dict):
                for key in ("findings", "leaks", "results", "issues"):
                    value = data.get(key)
                    if isinstance(value, list):
                        count += len(value)

        if count > 0:
            print(f"Gitleaks findings detected: {count}")
            print("Tip: remove leaked secrets with Leak-Lock:")
            print("  https://marketplace.visualstudio.com/items?itemName=NikolaReljin.leak-lock")
            print("  https://open-vsx.org/extension/nikolareljin/leak-lock")
            if fail_on_findings:
                sys.exit(3)
        else:
            print("No Gitleaks findings detected.")
        PY
      env:
        REPORT_FORMAT: ${{ inputs.report_format }}
        OUTPUT: ${{ inputs.output }}
        FAIL_ON_FINDINGS: ${{ inputs.fail_on_findings }}
