name: auto-tag-release-push
on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  pull-requests: read
  actions: write

jobs:
  tag:
    uses: ./.github/workflows/auto-tag-release.yml
    with:
      release_workflow: create-github-release.yml
