name: ci-helpers-deploy
on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: ubuntu-latest
      working_directory:
        type: string
        default: "."
      fetch_depth:
        type: number
        default: 0
      node_version:
        type: string
        default: ""
      java_version:
        type: string
        default: ""
      dotnet_version:
        type: string
        default: ""
      python_version:
        type: string
        default: ""
      go_version:
        type: string
        default: ""
      php_version:
        type: string
        default: ""
      deploy_command:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: ${{ inputs.fetch_depth }}
          fetch-tags: true

      - name: Setup Node
        if: ${{ inputs.node_version != '' }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ inputs.node_version }}

      - name: Setup Java
        if: ${{ inputs.java_version != '' }}
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: temurin
          java-version: ${{ inputs.java_version }}

      - name: Setup .NET
        if: ${{ inputs.dotnet_version != '' }}
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Setup Python
        if: ${{ inputs.python_version != '' }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ inputs.python_version }}

      - name: Setup Go
        if: ${{ inputs.go_version != '' }}
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ inputs.go_version }}

      - name: Setup PHP
        if: ${{ inputs.php_version != '' }}
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ inputs.php_version }}

      - name: Deploy
        shell: bash
        working-directory: ${{ inputs.working_directory }}
        run: |
          set -euo pipefail
          ${{ inputs.deploy_command }}
