name: NoseyParker Scan
description: Run NoseyParker scan in Docker and emit a report.
inputs:
  scan_path:
    description: Path to scan (relative to repo root).
    default: "."
    required: false
  image:
    description: Docker image for NoseyParker.
    default: ghcr.io/praetorian-inc/noseyparker:latest
    required: false
  datastore_dir:
    description: Directory in repo root to store NoseyParker datastore.
    default: .noseyparker
    required: false
  report_format:
    description: Report format (json or text).
    default: json
    required: false
  output:
    description: Output report file path.
    default: noseyparker-report.json
    required: false
  fail_on_findings:
    description: Fail when report contains findings (json only).
    default: "false"
    required: false
runs:
  using: composite
  steps:
    - name: Run NoseyParker scan
      shell: bash
      run: |
        set -euo pipefail
        scan_path="${{ inputs.scan_path }}"
        datastore_dir="${{ inputs.datastore_dir }}"
        report_format="${{ inputs.report_format }}"
        output="${{ inputs.output }}"
        image="${{ inputs.image }}"

        mkdir -p "$(dirname "$output")" "$datastore_dir"

        docker run --rm \
          -v "$GITHUB_WORKSPACE:/scan" \
          "$image" \
          scan --datastore "/scan/$datastore_dir" "/scan/$scan_path"

        docker run --rm \
          -v "$GITHUB_WORKSPACE:/scan" \
          "$image" \
          report --datastore "/scan/$datastore_dir" --format "$report_format" \
          > "$output"
    - name: Fail on findings
      if: ${{ inputs.fail_on_findings == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        report_format="${{ inputs.report_format }}"
        output="${{ inputs.output }}"

        if [[ "$report_format" != "json" ]]; then
          echo "fail_on_findings requires report_format=json" >&2
          exit 2
        fi

        python3 - <<'PY'
import json
import sys

with open("${{ inputs.output }}", "r", encoding="utf-8") as fh:
    data = json.load(fh)

count = 0
if isinstance(data, dict):
    for key in ("findings", "matches", "results", "issues"):
        value = data.get(key)
        if isinstance(value, list):
            count += len(value)
elif isinstance(data, list):
    count = len(data)

if count > 0:
    print(f"NoseyParker findings detected: {count}")
    sys.exit(3)

print("No NoseyParker findings detected.")
PY
